---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-atlas
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/sd109/flux-atlas
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-atlas
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-atlas
  path: "./deploy/manifests"
  prune: true
  timeout: 1m
