name: Run tests

on:
  workflow_call:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      # Also installs kubectl
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: integration-tests

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Install Flux CD on Kind cluster
        run: flux install

      - name: Apply test manifests
        run: |
          kubectl apply -f ui/tests/manifests --wait

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run API unit tests
        working-directory: api
        run: |
          cargo build
          cargo test

      - name: Setup UI toolchain
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install UI test dependencies
        working-directory: ui
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run UI tests
        run: |
          cd api && cargo run &
          cd ui && npm test
